

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
